# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwise_hellinger_test <- function(data_list, grid_points = 200L, bandwidth = NA_real_) {
    .Call(`_PkgDistributionCompare_pairwise_hellinger_test`, data_list, grid_points, bandwidth)
}

pairwise_ks_test <- function(data_list, n_terms = 100L) {
    .Call(`_PkgDistributionCompare_pairwise_ks_test`, data_list, n_terms)
}

